Import Library

In [124]:
import os
import numpy as np
from PIL import Image
import numpy as np
import math
from numpy.random import normal

Flatten

In [125]:
# Set the input directory path
input_directory = "../Dataset/Foto_Resize_70x70"

# List all folders in the input directory
folders = [f for f in os.listdir(input_directory) if os.path.isdir(os.path.join(input_directory, f))]
print(f"Found folders: {folders}")

# Initialize arrays for inputs and outputs
X = []
Y = []

# Create a mapping from folder names to one-hot encoded labels
label_map = {folder: idx for idx, folder in enumerate(folders)}
num_classes = len(folders)

# Process each folder and photo
for folder in folders:
    folder_path = os.path.join(input_directory, folder)
    
    # Sort the list of photos to ensure consistent order
    photos = sorted([p for p in os.listdir(folder_path) if p.endswith(('.png', '.jpg', '.jpeg'))])
    
    for photo in photos:
        photo_path = os.path.join(folder_path, photo)
        image = Image.open(photo_path)
        
        # Convert the image to a numpy array and flatten it
        image_array = np.array(image).flatten()
        X.append(image_array)
        
        # Create a one-hot encoded label
        label = np.zeros(num_classes)
        label[label_map[folder]] = 1
        Y.append(label)

# Convert lists to numpy arrays
X = np.array(X)
Y = np.array(Y)

print(f"Input array shape: {X.shape}")
print(f"Output array shape: {Y.shape}")

Found folders: ['Azmira', 'David', 'Dimas', 'Fadhli', 'Fadlin', 'Hafidz', 'Haidar', 'Hanna', 'Keiko', 'Khansa', 'Mikhael', 'Puti', 'Raesa', 'Satwika', 'Toni']
Input array shape: (1384, 4900)
Output array shape: (1384, 15)


Normalize X, Print Y

In [126]:
print(X)
xmax = X.max()
xmin = X.min()
X =  (X-xmin)/(xmax-xmin)
print(X)

[[218 220 222 ... 137 112 103]
 [253 252 251 ... 137 127 116]
 [106 117 133 ... 220 219 218]
 ...
 [213 213 214 ...  55  50  48]
 [214 214 214 ...  70  68  68]
 [ 51  48  51 ... 213 213 212]]
[[0.85490196 0.8627451  0.87058824 ... 0.5372549  0.43921569 0.40392157]
 [0.99215686 0.98823529 0.98431373 ... 0.5372549  0.49803922 0.45490196]
 [0.41568627 0.45882353 0.52156863 ... 0.8627451  0.85882353 0.85490196]
 ...
 [0.83529412 0.83529412 0.83921569 ... 0.21568627 0.19607843 0.18823529]
 [0.83921569 0.83921569 0.83921569 ... 0.2745098  0.26666667 0.26666667]
 [0.2        0.18823529 0.2        ... 0.83529412 0.83529412 0.83137255]]


In [127]:
print(Y)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


Initialize Layer

In [128]:
inputLayer = 2500
hiddenLayer = 1
outputLayer = 15

Calculating Weights for Input Layer to Hidden Layer

In [129]:
#70x70
#input = 4900, hiddenLayer = 1, neuron = 2

n = 4900
stddev = np.sqrt(2/n)
hiddenNeurons = 2
v = np.random.normal(loc=0, scale = stddev, size = (n, hiddenNeurons))
print(v)
np.shape(v)

[[-0.04687112 -0.03142038]
 [ 0.00034887 -0.00427716]
 [ 0.00269746 -0.00635548]
 ...
 [ 0.00106347 -0.0177076 ]
 [ 0.04548289 -0.00571417]
 [ 0.01258389 -0.01122113]]


(4900, 2)

In [130]:
vb = np.random.normal(loc=0, scale = stddev, size = (1, hiddenNeurons))
print(vb)
np.shape(vb)

[[-0.01984094  0.00283023]]


(1, 2)

Calculating Weights for Hidden Layer to Output Layer

In [131]:
#70x70
#input = 4900, hiddenLayer = 1, neuron = 2

n = 2
stddev = np.sqrt(2/n)
w = np.random.normal(loc=0, scale = stddev, size = (n, outputLayer))
print(w)
np.shape(w)

[[-0.32836003  1.0861446  -0.65963464  0.80986502  1.36049836 -0.34835851
  -0.69090084  0.02577142  0.91910916 -1.39979513  0.57802973 -0.17489527
   0.43604799  0.40059343 -1.67284986]
 [-0.06967294  1.95580632 -2.44439816  0.78627291  0.0535224   0.80411876
   0.05275637  0.99884072  0.59149713  0.63282047  1.45206662 -3.79697369
   0.62252057 -1.66850931 -1.34851056]]


(2, 15)

Calculating Bias Weight from Hidden Layer to Output Layer

In [132]:
wb = np.random.normal(loc=0, scale = stddev, size = (1, outputLayer))
print(wb)
np.shape(wb)

[[-1.17776205  0.20230774  0.67612097  0.31296104  1.08083766  0.87450015
  -0.03709175  0.07962697 -0.52236597  0.50318047 -1.2653688  -0.83717542
   0.32347868  0.07798862 -0.29364583]]


(1, 15)

Feedforward

In [133]:
z_in = np.matmul(X,v) + vb
print(z_in)
np.shape(z_in)

[[ 1.73828488 -0.39642524]
 [ 0.74300153  0.60127469]
 [ 1.30582168 -0.23960768]
 ...
 [ 1.40463552 -0.28552785]
 [ 0.55882333  0.74688209]
 [ 1.96448446 -0.12473617]]


(1384, 2)

In [134]:
# z = max([0,z_in])
z = np.maximum(0,z_in)
print(z)

[[1.73828488 0.        ]
 [0.74300153 0.60127469]
 [1.30582168 0.        ]
 ...
 [1.40463552 0.        ]
 [0.55882333 0.74688209]
 [1.96448446 0.        ]]


In [135]:
#y_in = np.dot(z,w) + wb
y_in = np.matmul(z,w) + wb
print(y_in)

[[-1.74854533  2.09033647 -0.47051195 ...  1.08145431  0.77433411
  -3.20153545]
 [-1.46362663  2.18529168 -1.28374332 ...  1.02176887 -0.62760227
  -2.34740111]
 [-1.6065417   1.62061891 -0.18524424 ...  0.8928796   0.6010922
  -2.47808945]
 ...
 [-1.63898822  1.72794503 -0.25042528 ...  0.93596718  0.64067638
  -2.64339017]
 [-1.41329477  2.27002739 -1.51817546 ...  1.03210193 -0.94433015
  -2.23565175]
 [-1.82282023  2.33602192 -0.61972103 ...  1.18008818  0.86494818
  -3.57993338]]


In [136]:
# y = fsigmoid(y_in)
y = 1 / (1 + np.exp(-y_in))
print(y)
np.shape(y)

[[0.14823077 0.88996038 0.38449508 ... 0.7467691  0.6844577  0.03910798]
 [0.18791327 0.8989209  0.2169137  ... 0.73531701 0.34805441 0.08727257]
 [0.16706931 0.83488047 0.45382092 ... 0.70948406 0.64590614 0.07740854]
 ...
 [0.16260278 0.84914938 0.43771883 ... 0.71828433 0.65490634 0.06639757]
 [0.19571491 0.90636411 0.17973035 ... 0.7373232  0.2800265  0.09659432]
 [0.13909581 0.91181674 0.3498449  ... 0.76496366 0.70369343 0.02712147]]


(1384, 15)

Back Propagation

In [137]:
#setiap unit output
#sigma_y = (Y-y)*f'(y_in) 
sigma_k = (Y-y)*np.exp(-y_in)/(np.exp(-y_in)+1)**2
print(sigma_k)
np.shape(sigma_k)

[[ 0.10754303 -0.08715462 -0.09099407 ... -0.14121778 -0.147826
  -0.00146962]
 [ 0.12392596 -0.08167785 -0.03684543 ... -0.14311174 -0.07897791
  -0.00695179]
 [ 0.11590826 -0.11509251 -0.11248745 ... -0.14623632 -0.1477261
  -0.00552824]
 ...
 [-0.0221405  -0.10877154 -0.10773182 ... -0.14534624 -0.14801147
   0.05787302]
 [-0.0308076  -0.0769215  -0.02649717 ... -0.14280306 -0.05645661
   0.07883467]
 [-0.01665647 -0.07331642 -0.07957343 ... -0.13753607 -0.1467264
   0.02567028]]


(1384, 15)

In [138]:
a = 0.2
z1 = np.zeros(15)
z2 = np.zeros(15)
z3 = np.zeros(15)
z1 = z[0]
z2 = z[1]
z3 = z[2]
print(z)


[[1.73828488 0.        ]
 [0.74300153 0.60127469]
 [1.30582168 0.        ]
 ...
 [1.40463552 0.        ]
 [0.55882333 0.74688209]
 [1.96448446 0.        ]]
