In [33]:
import numpy as np
from numpy.random import normal
import math

Weight Initialization with He

In [34]:
#50x50
#input = 2500, hidden layer = 1, neuron = 2
n = 2500
stddev = np.sqrt(2/n)
hiddenNeurons = 2
v = np.random.normal(loc=0, scale = stddev, size = (n, hiddenNeurons))
print(v)
np.shape(v)

[[-0.05130505 -0.02578975]
 [-0.00163621 -0.00733247]
 [-0.01253943  0.03208602]
 ...
 [-0.03483691 -0.00845545]
 [ 0.01945475  0.04037163]
 [-0.02865292  0.0230721 ]]


(2500, 2)

In [35]:
#70x70
#input = 4900, hiddenLayer = 1, neuron = 2

n = 4900
stddev = np.sqrt(2/n)
hiddenNeurons = 2
v = np.random.normal(loc=0, scale = stddev, size = (n, hiddenNeurons))
print(v)
np.shape(v)

[[ 0.02678651  0.00921741]
 [ 0.00089084  0.00889678]
 [-0.01075283 -0.02339878]
 ...
 [ 0.02782261  0.02630598]
 [-0.04833084 -0.06449617]
 [ 0.01387595 -0.00938012]]


(4900, 2)

In [37]:
#30x30
#input = 900, hiddenLayer = 1, neuron = 2

n = 900
stddev = np.sqrt(2/n)
hiddenNeurons = 2
v = np.random.normal(loc=0, scale = stddev, size = (n, hiddenNeurons))
print(v)
np.shape(v)

[[-0.00163303 -0.04368407]
 [-0.07560497  0.0440807 ]
 [-0.08900147 -0.04426218]
 ...
 [-0.02109804 -0.10316508]
 [ 0.00626729  0.00730243]
 [-0.05159767 -0.02713526]]


(900, 2)

Bias Weight Initialization with He

In [38]:
vb = np.random.normal(loc=0, scale = stddev, size = (1, hiddenNeurons))
print(vb)
np.shape(vb)

[[-0.01435054  0.03950624]]


(1, 2)